### ISSUE TITLE
Add setenv and chdir methods to the CLibrary

### ISSUE THREAD

**Issue by gnodet** [fusesource/jansi#196]

**Comment by oxc** [comment]
Could you explain why this was added? It does not seem to be called from the java code?

**Comment by gnodet** [comment]
They are both required by `mvnd` : https://github.com/mvndaemon/mvnd/blob/34779fd7a0279b8b4f54a93dcb85d373c5560d51/daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java#L668-L673

**Comment by oxc** [comment]
I see. Sounds to me that it was convenient to add them to Jansi because the infrastructure already exists, but they shouldn't really be in here but in a separate library. They seem to have nothing to do with Ansi terminal handling, and are not needed by any "normal" users of this library.

I have recently added a Pull request to a project introducing Jansi, and they have raised concerns about whether the library introduces any hard to control native behavior. I must agree that having unused functions in the native blobs that are not even used by the first party library feels somewhat conspicuous.

**Comment by garydgregory** [comment]
I agree with you, this belongs in something like JNA if it's not already in
there ;-)

Gary
