### ISSUE TITLE
Detect console width

### ISSUE THREAD

**Issue by pescuma** [fusesource/jansi#24]
Is it possible to create a method to detect the console width?

**Comment by gnodet** [comment]
If you want lowever level terminal interaction, have a look at the [jline3](https://github.com/jline/jline3) library.  It actually leverage jansi for windows support.

**Comment by garretwilson** [comment]
But what I'm not understanding is that if jline3 uses Jansi, then that would mean the capability could be done using just Jansi without the jline3 library, right? (i.e. if jline3 can do it using Jansi, can't anybody do it with Jansi?) So how does jline3 detect the console width using Jansi?

Or maybe I misinterpreted you when you said that jline3 "actually leverage jansi for windows support".

**Comment by garretwilson** [comment]
@pescuma I don't know why this ticket was closed, especially since Jansi actually provides a good way to detect the console width. There is no need I can see to use jline3, especially since, as noted, it may wind up using Jansi in the end anyway.

To answer your question, you can use [AnsiConsole.getTerminalWidth()](https://javadoc.io/static/org.fusesource.jansi/jansi/2.4.0/org/fusesource/jansi/AnsiConsole.html#getTerminalWidth()) to get the terminal width. That delegates to the stdout wrapper class it has created and eventually calls (on Windows) a `Kernel32.GetConsoleScreenBufferInfo()` method which is a native method, directly calling the [Windows API](https://docs.microsoft.com/en-us/windows/console/getconsolescreenbufferinfo)! This means it will be very efficient (taking less than 10,000 nanoseconds on my machine, which is well under a millisecond). Jansi comes with all the JNI files (such as a Windows DLL) for various systems.

If you want to just detect the width for `stdout` or `stderr` (taking into consideration it may be redirected), you can check just `AnsiConsole.out().getTerminalWidth()` or `AnsiConsole.err().getTerminalWidth()`, respectively. (`AnsiConcole.getTerminalWidth()` checks them both.)

**Comment by gnodet** [comment]
> But what I'm not understanding is that if jline3 uses Jansi, then that would mean the capability could be done using just Jansi without the jline3 library, right? (i.e. if jline3 can do it using Jansi, can't anybody do it with Jansi?) So how does jline3 detect the console width using Jansi?
> 
> Or maybe I misinterpreted you when you said that jline3 "actually leverage jansi for windows support".

There's history here.  The ticket was closed in 2017, way before those features were added to jansi.

**Comment by garretwilson** [comment]
> There's history here. The ticket was closed in 2017, way before those features were added to jansi.

Oh, I see. Well it's glad to know those features are there now. I hope my updates to this ticket can help someone else.
